on:
    push:
        branches:
            - main
    pull_request:

name: "Shell Lint"

jobs:
    shellcheck:
        name: Shellcheck
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Run Shell Lint
              uses: azohra/shell-linter@v0.6.0
